# ProxyVote, a service from Block Transfer

VERSION = "4.2.1"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
FEDERATION_SERVER = "https://stellarid.io/federation/"

[DOCUMENTATION]
ORG_NAME = "BlockTrans Syndicate"
ORG_DBA = "Block Transfer"
ORG_URL = "https://www.blocktransfer.io"
ORG_LOGO = "https://blocktransfer.io/logo.png"
ORG_DESCRIPTION = "A decentralized stock transfer agent protocol for global financial markets."
ORG_PHYSICAL_ADDRESS = "131 Ponce de Leon Ave NE, Ste 405, Atlanta, GA, 30308."
# ORG_PHONE_NUMBER = ""
# ORG_PHONE_NUMBER_ATTESTATION = ""
ORG_GITHUB = "blocktransfer"
# ORG_OFFICIAL_EMAIL = "stellar@blocktransfer.io"
ORG_SUPPORT_EMAIL = "support@blocktransfer.io"
ORG_LICENSING_AUTHORITY = "U.S. Securities and Exchange Commission"
ORG_LICENSE_TYPE = "Central Index Key"
ORG_LICENSE_NUMBER = "0001846058"

[[PRINCIPALS]]
name = "John F. Wooten, IV"
email = "john@blocktransfer.io"
github = "JFWooten4"
id_photo_hash = "0dce43292a7dd2c6ef021cca9f84330ceeec34e8587172453bc2b05f1bd13edd"
verification_photo_hash = "a3b5109c1afb0d7ce22780fc5a656bda0f24b63d4bbddcff35f44f0b8e62ff48"