# ProxyVote, a service from Block Transfer <blocktransfer.io>

VERSION = "4.2.1"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
FEDERATION_SERVER = "https://stellarid.io/federation/"
